services:
  - type: web
    name: rexify-bot
    env: node
    plan: free

    buildCommand: npm install
    startCommand: npm start

    envVars:
      - key: NODE_ENV
        value: production

      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "false"
